// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs82MJ-nAARkTx31wD8HzJfzqUxYrCYD8',
    appId: '1:633643758604:web:446b0fce4803472ca76a29',
    messagingSenderId: '633643758604',
    projectId: 'musicman-4a940',
    authDomain: 'musicman-4a940.firebaseapp.com',
    storageBucket: 'musicman-4a940.firebasestorage.app',
    measurementId: 'G-EBMDZMHX33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvL5iTCmAqJWTIpjXVgvTDgKVHhfYGlw',
    appId: '1:633643758604:android:a411863ced3c7fe9a76a29',
    messagingSenderId: '633643758604',
    projectId: 'musicman-4a940',
    storageBucket: 'musicman-4a940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYBHlLXOSEk68ymhb7jejJgi28H8RsgE',
    appId: '1:633643758604:ios:4ce18109510b8595a76a29',
    messagingSenderId: '633643758604',
    projectId: 'musicman-4a940',
    storageBucket: 'musicman-4a940.firebasestorage.app',
    iosBundleId: 'com.example.musicman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGYBHlLXOSEk68ymhb7jejJgi28H8RsgE',
    appId: '1:633643758604:ios:4ce18109510b8595a76a29',
    messagingSenderId: '633643758604',
    projectId: 'musicman-4a940',
    storageBucket: 'musicman-4a940.firebasestorage.app',
    iosBundleId: 'com.example.musicman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs82MJ-nAARkTx31wD8HzJfzqUxYrCYD8',
    appId: '1:633643758604:web:2e281a8b72333e1da76a29',
    messagingSenderId: '633643758604',
    projectId: 'musicman-4a940',
    authDomain: 'musicman-4a940.firebaseapp.com',
    storageBucket: 'musicman-4a940.firebasestorage.app',
    measurementId: 'G-Q99MME0D3S',
  );
}
